### ISSUE TITLE
Error when running joint_model: could not find function "bs"

### ISSUE THREAD

**Issue by tom-snir** [jackgisby/longitudinal_olink_proteomics#4]
I am attempting to analyze my own dataset, the first simple_mixed_de worked alright (had to duplicate my assay column as geneID) with a few warnings:

Warning: longer object length is not a multiple of shorter object length
Warning: longer object length is not a multiple of shorter object length

and generated the volcano plot (with results very different from what I expected or the original OlinkAnalyze package gave, still need to investigate)

However, when running the join_model on the sample date plasma_full, I get the following:

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'summary': could not find function "bs"

As far as I know, bs is a core R function, any advice regarding this?

Thanks in advance!

**Comment by jackgisby** [comment]
Hi @tom-snir,

If you're working with another proteomics dataset, I generally recommend using the original OlinkAnalyze package. I made some modifications to the version in this repository that were needed for our data, but may not be generally applicable. 

Alternatively, if you're working with our COVID-19 data, [this example script](https://github.com/jackgisby/longitudinal_olink_proteomics/tree/main/scripts) might help.

The specific issue with the joint model function should be resolved by loading library(splines). You might also need to load library(survival) and library(JMbayes).

**Comment by tom-snir** [comment]
@jackgisby 

Thanks, loading both those packages solved the issue, I'll close it.

Yes, I've used the original OlinkAnalyze package, but was interested in the modified version you used in the paper. What is most peculiar is that I am getting completely different results from the original package and the modified version, down to up-regulation in one and down-regulation in the other, both with very strong p-values. But as you say, perhaps the changes made are simply not generalized.

Thanks again for the help!

**Comment by jackgisby** [comment]
@tom-snir 

Not entirely sure why this would be, but see below for a couple of possibilities. If you try getting the package(s) to work, it would be worth checking that the fold change estimated by the model(s) reflects what you see in the raw data (e.g. if you see upregulation of IL6 in COVID-19 patients according to the model, as a sanity check I recommend making a boxplot comparing the raw protein abundance of IL6 in COVID-19 positive and negative patients).

**1 - Hardcoded variables**

Some of the variables in the code I wrote worked for my analysis, but were hardcoded. E.g. [the following line of code](https://github.com/jackgisby/longitudinal_olink_proteomics/blob/fc6c74d49240fa3058e97e231ad771775ceb63c4/OlinkAnalyze_Modified/R/linear_mixed_model.R#L368) extracts fold change as the second beta in the model. If your variable of interest is not the second term in the model, or your variable has more than two levels, this would be a problem.

**2 - If the protein results from each package are consistently opposite in each package, the problem might be how the variable is encoded.** 

It might be that one package is estimating mean(NEGATIVE) - mean(POSITIVE) and the other calculates mean(POSITIVE) - mean(NEGATIVE). See [here ](https://stats.stackexchange.com/questions/430770/in-a-multilevel-linear-regression-how-does-the-reference-level-affect-other-lev) for more information.

In the code from this repository, [the following lines](https://github.com/jackgisby/longitudinal_olink_proteomics/blob/fc6c74d49240fa3058e97e231ad771775ceb63c4/OlinkAnalyze_Modified/R/linear_mixed_model.R#L106-L119) convert the input variables to factors. Similar code is found in the [current version of the OlinkAnalyze package](https://github.com/Olink-Proteomics/OlinkRPackage/blob/bd1260d9bbd79837991e8bc71c11fa310accbf3b/OlinkAnalyze/R/linear_mixed_model.R#L142-L152).

If this is the problem, it might help to convert the variable of interest to a factor before running the packages.
